### PR TITLE
Assorted WaveRenderer UI improvements

### PR DESCRIPTION
**Pull request by fdxmw**
See the updated screenshots and tests for a preview:

- Add minor tick marks to rulers. This makes it easier to identify cycle boundaries
- Use different Unicode and ASCII characters for clearer display
  - Use different line drawing characters for more continuous lines
  - 'x' is a confusing separator in ASCII output as hex values also contain x's, use '|' instead
- When `extra_line` is enabled, draw additional major tick marks between signals
- Disable `segment_delim` by default as the additional major ticks show roughly the same thing in less horizontal space
- Make all segments the same length. Previously the first segment was one character longer

Also:
- Upgrade tox to use python3.8 and disable python2.7. Python 2.7 and 3.7 are currently not easy to install (at least on my macos machine)

### CODE REVIEW

**Comment by mdko** [comment]
I think all of this looks great! I'm torn between the old characters used for up/down in `Utf8WaveRenderer` ([link](https://github.com/UCSBarchlab/PyRTL/pull/428/files#diff-834632e0dd1a4f59d1d374a03b051d305d34aa99376646db9a8cc4dc6057b8f1L1003)) (which match the transitions on binary signals) and the new ones you've chosen (which I find do make it easier to read). Just putting my two cents out there.

**Comment by fdxmw** [comment]
> I'm torn between the old characters used for up/down in `Utf8WaveRenderer` ([link](https://github.com/UCSBarchlab/PyRTL/pull/428/files#diff-834632e0dd1a4f59d1d374a03b051d305d34aa99376646db9a8cc4dc6057b8f1L1003)) (which match the transitions on binary signals)

Thanks for taking a look! Can you help me understand how the old up/down characters matched the transitions on binary signals? For me the old characters didn't quite align, see the little bumps and gaps on [screenshot](https://github.com/UCSBarchlab/PyRTL/blob/development/docs/screenshots/pyrtl-statemachine.png), while the new characters seem to align for various fonts I've experimented with ([screenshot](https://github.com/fdxmw/PyRTL/blob/ui/docs/screenshots/pyrtl-statemachine.png))

**Comment by fdxmw** [comment]
Also this is all very subjective, I think these are improvements but I'm happy to make changes if people see things differently :)

**Comment by mdko** [comment]
> > I'm torn between the old characters used for up/down in `Utf8WaveRenderer` ([link](https://github.com/UCSBarchlab/PyRTL/pull/428/files#diff-834632e0dd1a4f59d1d374a03b051d305d34aa99376646db9a8cc4dc6057b8f1L1003)) (which match the transitions on binary signals)
> 
> Thanks for taking a look! Can you help me understand how the old up/down characters matched the transitions on binary signals? For me the old characters didn't quite align, see the little bumps and gaps on [screenshot](https://github.com/UCSBarchlab/PyRTL/blob/development/docs/screenshots/pyrtl-statemachine.png), while the new characters seem to align for various fonts I've experimented with ([screenshot](https://github.com/fdxmw/PyRTL/blob/ui/docs/screenshots/pyrtl-statemachine.png))

Oh, sorry, I think I was looking at the wrong picture! Your new version looks much better, including those transitions. I’m 100% pro your changes. 😎

**Comment by fdxmw** [comment]
A number of updates to this pull request:

1. Rising and falling edges are now vertical. This is done by rendering binary wires across two lines in the terminal.
2. Added an environment variable option PYRTL_RENDERER to select a particular renderer. There are currently 5:
   1. 'powerline' : Render value transitions with powerline triangle glyphs. This produces the familiar hexagon shapes that are common in logic analyzers. Binary wires are rendered with vertical rising and falling edges. Unfortunately powerline glyphs are not standard, and there doesn't seem to be a way to detect their availability, so users must manually enable this option.
   2. 'utf-8' : Default renderer on all platforms except Windows. Binary wires are rendered with vertical rising and falling edges, and values are rendered in rectangles.
   3. 'utf-8-alt' : Binary wires are rendered with diagonal rising and falling edges, and values are rendered in rectangles.
   4. 'cp437' : Default renderer on Windows. Binary wires are rendered with vertical rising and falling edges, using only the box drawing characters in 8-bit ASCII. 
   5. 'ascii' : Basic renderer, limited to 7-bit ASCII.
3. Removed `render_trace()`'s `segment_delim` and `extra_line` options. `extra_line` is now mandatory with two-line rendering for binary wires, and `segment_delim` complicates the code and doesn't seem to be used.
4. Decreased `render_trace()`'s default `segment_size` to 1. I often find myself counting cycles between tick marks, and I find it's much easier to just read the cycle number from the ruler.

**Review by mdko — COMMENTED** [review]
Looks great!

**Pull request merged**
